name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/my-project-image:latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run build
      run: |
        mkdir build
        cd build
        cmake ..
        make
        cd ..

    - name: Run tests
      run: ceedling test:all

    - name: Generate reports
      run: ceedling gcov:all