name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run tests inside Docker container
      run: |
        docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        docker run --rm -v "$(pwd):/app" -v "$(pwd)/build/reports:/app/build/reports" ghcr.io/${{ github.repository }}/my-project-image:latest

    - name: Upload reports as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ceedling-reports
        path: build/reports
